use MagniDB
db.addUser({user: "Magni", pwd: "4rg0s", roles: [ "dbAdmin" ]})
db.users.save({"cn": "Francisco", "role":"ROLE_ADMIN", "username":"fgmontoro"})
db.tags.save ( {tag:"SAP"})
db.tags.save ( {tag:"SAP Avanzados (wm, srm, apo, real state)"})
db.tags.save ( {tag:"JDE"})
db.tags.save ( {tag:"Otros ERPs (navision, axapta, ovebd)"})
db.tags.save ( {tag:"BI"})
db.tags.save ( {tag:"ETL"})
db.tags.save ( {tag:"EPM"})
db.tags.save ( {tag:"Big Data"})
db.tags.save ( {tag:"CRM"})
db.tags.save ( {tag:"Sistemas Unix"})
db.tags.save ( {tag:"Entornos Microsoft (sistemas, .net, office)"})
db.tags.save ( {tag:"Sistemas Mainframe"})
db.tags.save ( {tag:"Almacenamiento y back up"})
db.tags.save ( {tag:"Comunicaciones"})
db.tags.save ( {tag:"Seguridad"})
db.tags.save ( {tag:"CPD"})
db.tags.save ( {tag:"Base de Datos"})
db.tags.save ( {tag:"Servidores de Aplicaciones"})
db.tags.save ( {tag:"Transaccionales"})
db.tags.save ( {tag:"SOA/BPM"})
db.tags.save ( {tag:"Monitorización APM"})
db.tags.save ( {tag:"Automatización (operación, config, despliegues)"})
db.tags.save ( {tag:"Cloud"})
db.tags.save ( {tag:"Aplicaciones sectoriales"})
db.tags.save ( {tag:"Metodologías y calidad"})
db.tags.save ( {tag:"Java"})
db.tags.save ( {tag:"Java J2EE"})
db.tags.save ( {tag:"Front (Javascript, HTML5)"})
db.tags.save ( {tag:"SQL, PL/SQL, ProC"})
db.tags.save ( {tag:"C/C++/C#"})
db.tags.save ( {tag:"PHP, Phyton, Perl, Scripting"})
db.tags.save ( {tag:"Desarrollo Legacy (cliente servidor, Visual Basic"})
db.tags.save ( {tag:"Movilidad (iOS, Android)"})
db.tags.save ( {tag:"Maquetación, diseño gráfico"})
db.tags.save ( {tag:"Portales, buscadores y gestión de contenidos"})
db.tags.save ( {tag:"Gestión documental"})
db.tags.save ( {tag:"eCommerce"})
db.tags.save ( {tag:"Silverlight (y Entity Framework)"})
db.tags.save ( {tag:"Estándares Integración Sanidad (HL7, SNOMED)"})
db.tags.save ( {tag:"Programación periféricos"})
db.tags.save ( {tag:"Entorno Host (Cobol, Cics, DB2)"})
db.tags.save ( {tag:"Bankshere"})
db.tags.save ( {tag:"No aplica"})
db.tags.save ( {tag:"Base de Datos SyBase"})
db.tags.save ( {tag:"Base de Datos DB2"})